// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gigimbmleqeipkczjnqf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdpZ2ltYm1sZXFlaXBrY3pqbnFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxOTM2OTksImV4cCI6MjA2ODc2OTY5OX0.CVqmgRQhiUNZTYNjox5WMOuRgtq4B8qbPLa0wIuv1IM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});